from __future__ import annotations

from typing import Tuple


DEFAULT_TEXT_COLOR = 0xFF252525
DEFAULT_TEXT_SIZE = 17.0
DEFAULT_TEXT_FONT = "DejaVu Sans"
DEFAULT_RENDER_DPI = 100.0

AUTO_TEXT_SCALE_PRESETS: Tuple[Tuple[float, float], ...] = (
    (720.0, 1.6),
    (961.0, 3.2),
    (1080.0, 2.19),
)
AUTO_TEXT_SCALE_TOLERANCE = 24.0
MIN_TEXT_SCALE = 0.5
MAX_TEXT_SCALE = 8.0

IMAGE_LAYOUT_NORMAL = 0
IMAGE_LAYOUT_WRAP_TEXT_AROUND = 1
IMAGE_LAYOUT_WRAP_TEXT_BEHIND = 2
IMAGE_LAYOUT_USE_DEFAULT = 3

PDF_OVERLAY_TAGS_TO_STRIP: Tuple[str, ...] = (
    "SPenSDK_PAGE_LIST",
    "SPenSDK_PAGE_SINGLE",
    "SPenSDK_HIGHLIGHT_PAGE_LIST",
    "SPenSDK_HIGHLIGHT_PAGE_SINGLE",
    "SPenSDK",
)

SPAN_TYPE_FOREGROUND = 1
SPAN_TYPE_FONT_SIZE = 3
SPAN_TYPE_FONT_NAME = 4
SPAN_TYPE_BOLD = 5
SPAN_TYPE_ITALIC = 6
SPAN_TYPE_UNDERLINE = 7
SPAN_TYPE_HYPER_TEXT = 9
SPAN_TYPE_BACKGROUND = 17
SPAN_TYPE_TIMESTAMP = 19
SPAN_TYPE_STRIKETHROUGH = 20

PARAGRAPH_TYPE_DIRECTION = 1
PARAGRAPH_TYPE_INDENT = 2
PARAGRAPH_TYPE_ALIGN = 3
PARAGRAPH_TYPE_LINE_SPACING = 4
PARAGRAPH_TYPE_BULLET = 5
PARAGRAPH_TYPE_PARSING_STATE = 6
